name: 'terraform fmt'
on: [push]
jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive